package.json

The `files` property limited publishing to `index.js` and `package.json` alone and skipped rest of the files.

Fix web-components package.json to publish all files in the distribution.

---

package.json
src/components/Message/Message.tsx

Current page message in terraware-web needs support from array of strings for title and body (because of snackbar).
We can do extra handling in terraware-web instead but this PR might make it cleaner.

Support arrays of strings in messages

---

.github/workflows/design-workflow.yml

This PR removes dependencies from `yarn install` for the design workflow.
We only need dev dependencies installed for `yarn build-dictionary` - no need to download mui.
The speedup difference is now 40s versus 2 minutes and 30 seconds to download dependencies.

speed up design workflow by removing dependencies for yarn install

---

package.json
src/components/Textfield/Textfield.tsx
src/components/Textfield/styles.scss
src/stories/TextfieldNew.stories.tsx

This is needed for some new tooltips in the text field labels.

SW-1570 Add tooltip support to textfield labels

---

package.json
src/components/Select/SelectT.tsx
src/stories/Select.stories.tsx

The selectedValue was being set programmatically in my previous change https://github.com/terraware/web-components/commit/940359e9939e99dfc65446da571df396b4eab869#diff-3eff1d6531741c6efbea89561d7b39aa17e4f3e8f4f26d3f8b3942d89801fa2d
This breaks the ability to test selectedValue using the props form in storybook.
This PR change allows modifying and pre-selecting the selectedValue.

Fix Select component story to allow modifying the 'selectedValue'.

---

package.json
src/components/DatePicker/styles.scss
src/stories/DatePicker.stories.tsx

- currently uses parent background
- updated storybook to capture this behavior

SW-1831 add white background to datepicker text input

---

package.json
src/components/IconTooltip/index.tsx

This PR includes a few fixes related to styling:
- `IconTooltip` popover arrow isn't centered
- `IconTooltip` arrow sometimes appears disconnected
- `IconTooltip` icon sometimes renders too small

SW-1755: Add Species Tooltips (Follow ups)

---

package.json
src/components/Autocomplete/styles.scss
src/components/Button/styles.scss
src/components/DatePicker/styles.scss
src/components/DialogBox/styles.scss
src/components/ErrorBox/styles.scss
src/components/Message/styles.scss
src/components/Navbar/styles.scss
src/components/Select/styles.scss
src/components/Textfield/styles.scss

- import `terrware.scss` into stylesheets
- use new semantic color token names
mappings per the [semantic mapping spreadsheet](https://docs.google.com/spreadsheets/d/1ECFEO33DP0GgesPagynY5MIIx_4lFn3rJh_PWjcfqLI/edit?usp=sharing)

SW-2021 Replace Design Token Names

---

package.json
src/components/table/index.tsx

Return the column from where the row was clicked when executing rowClicked function. This change is needed because we need to open different modals on rowClick depending on the column on seedlings table. Tested with changes from withdrawal and details.

Send fromColumn value when clicking a column-row on table

---

package.json
src/components/Button/styles.scss

Forgot to include passive and secondary icon-only button styling updates with my last PR.  This should fix all icon-only buttons.

SW-2040 Update passive icon-only button styling

---

package.json
src/components/table/index.tsx

Table already had an option to make the row clickable or not. The problem was that if the row was not clickable, the checkbox didn't worked.
With this change if the row is clickable it will continue working as it used to, but if the row is not clickable only clicking on the checkbox will work.
Already tested with terraware-web

SW-2093 Select row only when clicking checkbox

---

package.json
src/components/Select/Select.tsx
src/components/Select/SelectT.tsx
src/components/Select/styles.scss

- Create new prop "allowEditingValue" to allow writing on selects.
- When select is read-only, don't allow user to change the value (not only by writing but also from selecting a new option)
- I will update terraware-web to use "allowEditingValue"

Create "allowEditingValue" prop to select

---

package.json
src/components/Textfield/Textfield.tsx
src/components/Textfield/styles.scss
src/stories/TextfieldNew.stories.tsx

- when used as right icon,
- make it 16x16
- add some padding-right
- add right icon cancel option to story

Adjust Cancel Icon Size for TextField

---

package.json
src/components/Textfield/styles.scss

- incorrectly used padding instead of margin, which 
allowed the icon to become squished
- change spacing to margin-right

Fix TextField Cancel Icon Sizing

---

package.json
yarn.lock

The dependabot vulnerabilities stem from storybook, upgrading to a patched version.
Tested storybook stories.

Upgrade loader utils in web-components to avoid vulnerabilities

---

.github/scripts/compare-artifact-package-versions.sh

- avoid publishing npm if version already exists
- using `npm view` command to check if the version exists
- output of npm view is sent to curses so saving that to a file for checking

SW-2286 Fix web-components build on main branch

---

.github/scripts/compare-artifact-package-versions.sh

The previous version of the script used
`npm view @terraware/web-components@${PACKAGE_JSON_VERSION} maintainers`
to check for the existence of a package version.
If the version did not exist, this resulted in an error instead of
no output as expected by the remainder of the script.
Example:
```
Checking if version exists in npm repository
npm ERR! code E404
npm ERR! 404 No match found for version 2.0.26
npm ERR! 404 
npm ERR! 404  '@terraware/web-components@2.0.26' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-[12](https://github.com/terraware/web-components/actions/runs/3604879723/jobs/6074700271#step …
```

Update NPM Version Lookup

---

.github/scripts/compare-artifact-package-versions.sh

Didn't realize that
`npm show @terraware/web-components versions --json | grep ${PACKAGE_JSON_VERSION} > /tmp/npm-output`
was failing with an error if the version didn't exist.
Replace with something that works.

Update npm version lookup 2

---

.github/scripts/compare-artifact-package-versions.sh

- the previous approach `npm show <version> <property>` was in the right direction as it checks for the specific version directly
- we just need to handle the error, which can be done in the script

Handle error response when npm show package-version returns an error

---

package.json
src/components/Navbar/styles.scss

This PR applies the style `mix-blend-mode: multiply` to the `NavBar` to make it easier for users to see the Contact Us nav item.

SW-2432: Fix Contact Us Navigation Item is Difficult to See

---

package.json
src/components/Navbar/styles.scss

This PR is a follow-up to adjust the newly added `mix-blend-mode: multiply` style rule to the `NavBar` when it's transparent, resolving an issue spotted by @hannah-cai [in a related PR](https://github.com/hannah-cai).

SW-2432: Fix Contact Us Navigation Item is Difficult to See (Follow-up)

---

package.json
src/components/Navbar/styles.scss
src/components/table/TableCellRenderer.tsx

- set 14px as table cell font size
- set nav color as tw-clr-txt
- feel free to play around with the vercel/storybook link

Fix font-color on nav, fix font-sizes on table cells

---

package.json
src/components/Checkbox.tsx
src/components/table/TableHeader.tsx
src/components/table/index.tsx
src/stories/Checkbox.stories.tsx
src/stories/Table.stories.tsx

- border radius and width are not fixed since it's an icon not css
- added comment in figma for ^
- more fixes to be done in web repo
- check out vercel

SW-2490 Checkbox style fixes

---

package.json
src/components/Autocomplete/Autocomplete.tsx
src/components/Autocomplete/styles.scss
src/components/Select/styles.scss
src/stories/Autocomplete.stories.tsx

- update chevron/caret to use homegrown icon as per designers' request
- support complex objects of type { label: string, value: any } so we can support selecting values based on unique values/ids
- some other minor style fixes
- pre-requisite for some withdrawal log / plants dashboard features
- remove V1 deprecated functionality

SW-2509 Autocomplete component enhancements and fixes

---

package.json
src/components/Autocomplete/Autocomplete.tsx
src/stories/Autocomplete.stories.tsx

Replace use of inputValue with value because:
- inputValue only sets a value for the Input component
- The value prop sends the passed value through getOptionLabel and compares with the options list.

SW-2537 Fix preselected value on autocomplete

---

package.json
src/components/Autocomplete/Autocomplete.tsx

Need a way to find which field the error text is attached to.  This follows a pattern that most of the other error text fields are already following.

SW-2608 Add ID to autocomplete to allow for easier tracking

---

package.json
yarn.lock

This reverts commit https://github.com/terraware/web-components/commit/f6248f4b6a0893dd7e756d41a619b0d65f8ebe0d.
- something new in the styles update is breaking terraware-web.. will follow up later as bandwidth permits

Revert "Bump @mui/styles from 5.9.3 to 5.11.2 (#225)"

---

package.json
src/components/DatePicker/DatePicker.tsx
src/stories/DatePicker.stories.tsx

The Datepicker component may now accept a time zone and locale as props.
Changing the time zone between e.g. Pacific/Honolulu and Asia/Tokyo, causes the current date to shift, indicating that the component is respecting the change in time zone:
Changing the locale causes the language of the datepicker to change:

SW-2677 Time Zone and Locale for Datepicker

---

package.json
src/components/DatePicker/DatePicker.tsx

Now temporalValue is used to show the datepicker value and that value is initialized with the initial value that comes from props. But if that initial value changes, the datepicker does not updates its temporal value.
Added a useEffect to update temporalValue if 'values' props changes.
Also return selectedValue as a string to consider the timezone

Update datepicker value when received value changes

---

.github/workflows/open-pr.yml

Only run when PR is opened to avoid inadvertently adding patch labels.

Auto-version Comment and Label Only on PR Opened

---

src/components/DatePicker/DatePicker.tsx
src/components/ProgressCircle/ProgressCircle.tsx
src/components/TextTruncated/index.tsx
src/components/table/EnhancedTableToolbar.tsx
src/components/table/TableCellRenderer.tsx
src/components/table/index.tsx
src/components/table/types.ts
src/stories/ProgressCircle.stories.tsx
src/stories/Table.stories.tsx
src/stories/TextTruncated.stories.tsx

Add properties to components that can show text or punctuation to allow (or 
rather, require) callers to pass in appropriately localized values. In cases
where the localized strings need to be rendered dynamically, callers pass in
functions that return the strings.

SW-2733 Support localized content

---

src/components/MultiSelect/index.tsx
src/components/MultiSelect/styles.scss
src/components/Pill/index.tsx
src/components/Pill/styles.scss
src/index.ts

- `align-items: flex-start` to position the chevron correctly
- change IconButton to a div to avoid capturing focus and then blurring
- rm padding in pill when there is no label

MultiSelect Fixes

---

src/components/TextTruncated/index.tsx
src/stories/TextTruncated.stories.tsx

- optionally render a placeHolder in case of empty stringList
- correctly use the listSeparator

Fix TextTruncated to Accept an Empty List of Strings

---

src/components/DatePicker/DatePicker.tsx

On datepicker component when pressing any key, if the value is not a valid date, we just save the value in "temporalValue" variable and the value (of the component) is set to null.
We were reseting the temporal value to null for the first key pressed because temporalValue was the key pressed, then value was set to null (because the value was not valid), and then temporalValue was set again to null because it was different from the temporal value.
The fix is to set temporal value equal to "value", only if value is not null

Fix datepicker first keypress ignored

---

package.json
yarn.lock

The @mui/styles bump from 5.11.9 to 5.11.12 (b20bedcf41de190215a1785e44787cbbbe8c995c) caused some kind of problem with theme initialization. Reverting that commit fixes the problem.

Revert @mui/styles upgrade

---

src/components/Textfield/Textfield.tsx

[SW-3184](https://terraformation.atlassian.net/browse/SW-3184) mention that values are being changed while scrolling when editing an inventory batch. I guess this behavior is unwanted in all inputs, that's why I'm adding the change here
[SW-3184]: https://terraformation.atlassian.net/browse/SW-3184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SW-3184 Disable scroll on number input fields

---

src/components/Textfield/Textfield.tsx
src/components/Textfield/styles.scss
src/stories/TextfieldNew.stories.tsx
yarn.lock

When in display mode, setting the preserveNewlines prop to true will cause newlines to be displayed. This is off by default, preserving the previous behavior of collapsing newlines.

SW-3434 Textfield Can Preserve Newlines

---

src/components/table/sort.ts
src/stories/Table.stories.tsx

The problem was with using parseFloat. It was returning the value up to the dash character -, ignoring the characters following it. So it was basically comparing the year, if the dates were all same year it didn't change anything when sorting (it did "sort" if you had dates from different years)
Change to use it Number, so that if it cannot compare values as a number, it will continue the logic to compare as a string.
Added a number column and a date column to the stories to test the change

SW-3503 Fix cannot sort table columns that show dates

---

.github/workflows/design-workflow.yml

- we have another deployment action that takes care of version bumps
- i would prefer for design-changes workflow to add a 'patch' label to the PR automatically, will see how we can do that

Skip package/version bump in design-changes workflow

---

src/components/DialogBox/styles.scss
src/components/ViewPhotosDialog/index.tsx

The DialogBox component had the `scrolled` prop, which I had missed
earlier. Use that for ViewPhotosDialog instead of making all dialog
boxes scrolled.

Use DialogBox Scrolled Prop

---

src/components/ViewPhotosDialog/index.tsx

The prev/next buttons' disabled state was not being updated on first load. This is exemplified by the case where only one photo was shown. 
This is fixed by adding a call to handleChange in the [initialSelectedSlide, open] useEffect. Thus, it should only be called additionally when the dialog is first opened.

Update Button Enabled/Disabled on Open

---

src/components/Navbar/NavSection.tsx
src/components/Navbar/Navbar.tsx
src/components/Navbar/styles.scss
src/stories/Navbar.stories.tsx

- the close icon should be on the left, not right
- also remove extra margin for titles that aren't separated by a divider, this no-separator option was added for funder portal but style wasn't adjusted
- does not affect the terraware use-case

Fix mobile nav menu styles in web-components

---

src/components/ViewPhotosDialog/index.tsx

- removed the height setting, which triggers loading thumbnails instead of full images
- this leaves it to the client to decide which image to view

Allow rendering full images in the view photos dialog

---

src/components/DatePicker/DatePicker.tsx

- we were using date-fns as the date library with `yyyy-MM-DD` as the date format
- with i18n timezones project, we switched to moment but missed updating the format to `YYYY-MM-DD`  [documented format for year](https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/)
- `yyyy` has different semantics in moment and was causing the issues
- this PR updates the date format for moment (`YYYY-MM-DD`)

SW-3345 Fix the date format in datepicker

---

src/components/Icon/Icon.tsx

- make it easier to fill an icon with color
- avoids having to override fill with nested css
- did not extend Button with similar pattern, different use-case (icon fill is propagated from button)

SW-3712 add a fillColor property on Icon component

---

src/components/Tabs/index.tsx
src/stories/Tabs.stories.tsx

- introduce id in tabs, which will be the tab's value
- the label alone will be the i18n friendly string
- otherwise client code cannot depend on a deterministic id

SW-3940 Fix tabs component to not depend on i18n string value 

---

.github/workflows/publish-rc.yaml

Using this https://github.com/actions/checkout/issues/331#issuecomment-1567674767 to get the RC publish workflow working. 
See this for more info https://terraformationteam.slack.com/archives/C01C69KA23Y/p1694187601980789

Fix the `issue_comment` "RC publish" workflow

---

.github/workflows/publish-rc.yaml
package.json

Dump GH context to see if I can determine why the Publish RC job is firing even when the comment does not contain 'publish rc'

Debug Publish RC job

---

package.json
src/components/table/EnhancedTableToolbar.tsx
src/components/table/index.tsx
src/stories/Table.stories.tsx

- to be used in TF Contact selection

SW-4239 Add support for showing tooltips in table topbar buttons

---

src/components/MultiSelect/index.tsx
src/stories/MultiSelect.stories.tsx

The previous PR that added this functionality did not work as expected, and required the user to double click out of the Popover if they had focused and blurred the MultiSelect _within_ the Popover.
The implementer of this MultiSelect-within-Popover-with-desired-blur/closing-behavior unfortunately needs to implement a cheeky setTimeout for the functionality to work as expected. This is because the state of the component updates from the onBlur event resolution before the onClick event resolves, resulting in an impossible (at least through my many attempts) situation to achieve the desired effect.

Fix MultiSelect-within-Popover functionality

---

src/utils/text.test.ts
src/utils/text.ts

Recently table column headers were converted to title case.  But we have at least one acronym that should not be title cased (IUCN)

SW-4918 Don't title case acronyms

---

package.json
src/components/FileChooser/index.tsx

Allow the file chooser to be configured to accept all file types.

SW-5066 Don't require MIME types in file chooser

---

src/components/Separator/index.tsx

- Update the default separator color to `tw-clr-brdr-tertiary`
- Allow for consumer to pass in a different color (deliverable view uses `tw-clr-dvdr-fill`

Fix Separator color

---

package.json
src/components/Textfield/Textfield.tsx
src/components/Textfield/TruncatedTextArea.tsx
src/stories/TextfieldNew.stories.tsx

- Add `TruncatedTextArea` component which renders conditionally within the `Textfield` if we are using `type='textarea'` and a truncation config is passed in
- Since we can't predict how the text will wrap on the page, we need to measure it on the page, as a result, the truncation config needs to have a `maxHeight` which is cleanly divisible by the line height for the value text, otherwise you will see things get cut off.
- I decided this was more simple than measuring and then figuring out what the number of lines is, and then slicing the value. Hopefully it is OK.

SW-5091 Truncated multi line text

---

package.json
src/components/Button/Button.tsx
src/components/Confirm/index.tsx
src/components/DialogBox/DialogBox.tsx
src/index.ts
src/stories/Confirm.stories.tsx

- to simplify a confirm modal creation
- supports various configurations

SW-4969 Generic confirm dialog component

---

package.json
src/components/Textfield/Textfield.tsx

Since `useStyles` is deprecated, add ability to pass in component specific styles from consumer. For now only `textarea` is supported

Pass component specific styles into `Textfield`

---

src/components/Select/SelectT.tsx
src/stories/Select.stories.tsx

- for editable dropdowns with dynamic options that are set based on user typed input, the dropdown transitions between being-shown and not-being-shown and back to being-shown
- when the dropdown is first shown, we calculate the position of the dropdown based on anchor element, this works fine
- if user continues typing and we no longer have options to show, the dropdown is hidden away at the top of the page
- if user continus typing and we have options again, the dropdown is visible again but the position is now at the top of the page
- the code that calculates position of dropdown was not triggered when dropdown transitions from not-being-shown to being-shown
- fixed that by making sure we calculate dropdown position if we transition from not having results to having results
- added …

SW-4662 Fix bug where 'fixedMenu' dropdowns were being shown above the anchor

---

package.json
yarn.lock

This PR adds a package resolution for `@babel/traverse` @ `7.24.1` to resolve a [critical vulnerability](https://github.com/terraware/web-components/security/dependabot/100).
I attempted to manually update any packages that depended on an older version but there are many packages that required updating including multiple packages for both babel & storybook. Didn't want to go down a rabbit hole with updating too many dependencies, but will re-visit if we think it's necessary. I decided to check the changelog for breaking changes and didn't find any between the oldest and latest versions of `@babel/traverse` being used (`7.1.6` & `7.24.1`). Since there are no breaking changes adding this package resolution should be safe.
Happy to re-visit updating all packages that depend on …

Add package resolution for @babel/traverse @ 7.24.1

---

src/components/table/TableCellRenderer.tsx

Adding this style with the basic styles for the table cells, because we want it to apply it in every cell

SW-4795 Apply "font-variant-numeric: tabular-nums" to all table columns

---

src/components/IconTooltip/index.tsx
src/components/table/TableHeaderItem.tsx
src/stories/Table.stories.tsx

Previously the label was aligned to right, but not the drag, sort and tooltip icons. Reorder all icons correctly when column is right-aligned
Sort icon
Drag icon

Align table header label and icons to the right when column is right aligned

---

package.json
src/components/Select/SelectT.tsx
src/components/Select/styles.scss
src/stories/Select.stories.tsx

- use state + css to avoid showing the dropdown until it is positioned

SW-4662 Avoid flash of dropdown menu before it's position is calculated/repositioned

---

package.json
src/components/Select/SelectT.tsx
src/stories/Select.stories.tsx

- previously the fixedMenu will be fixed during scroll and separated from input component
- added a scroll event handler to reposition menu
- updated story to enable scrolling

SW-4662 More fixedMenu fixes, handle scroll

---

src/components/Select/SelectT.tsx

- the resize happens as part of existing code when it repositions the menu during a window resize
- skip the resize if this is part of scroll

SW-4662 Don't resize dropdown during scroll

---

package.json
src/components/DatePicker/DatePicker.tsx

- the x-date-pickers luxon adapter is off mui5.x which has bugs
- specifically uses `instanceof DateTime` to check for a luxon dates, instanceof does not work across namespaces (npm package scope vs root terraware-web scope)
- this was preventing min/max date props from working across namespaces
- same for setting the value of DatePicker without a toISO conversion
- moved to @date-io/luxon which uses luxon's isDateTime function to compare dates
- this fixes all the issues previously observed (cannot delete characters, min/max dates not working)

SW-5218 Fix datepicker adapter for luxon

---

package.json
yarn.lock

- current babel-loader uses older dependencies that are insecure
- bumping node to 18 causes security errors 'digital envelope routines::unsupported' since babel-loader was using md4 instead of md5
- bumping babel-loader to version 9 fixes this error, we can bump node version to 18 in vercel with this change
- note that this does not upgrade all babel versions, separate task

SW-4653 Bump babel-loader version for node 18 compatibility in vercel

---

src/components/DialogBox/DialogBox.tsx
src/stories/DialogBox.stories.tsx

With this change all dialog boxes will be closed when clicking outside.
Added a new story where the dialog box can be opened/closed to show the new behavior.

SW-5221 Click out of dialog boxes to close

---

src/components/Textfield/Textfield.tsx

A small follow-up PR to add the `sx` prop to the `TextField` component, which was overlooked in the previous PR.

SW-53417: Remove makeStyles everywhere in Terraware web (follow-up)

---

src/components/table/TableCellRenderer.tsx

The root in the classes object for typography meant that the style should be applied to the MUI root class. With MUI 5 we don't need to do that, just set the max-width to the sx object

Truncate table cell

---

src/components/table/TableHeader.tsx
src/components/table/TableHeaderItem.tsx

When adding the "Density settings" the padding of the headers were disabled, but this was not necessary. Revert it to have the padding back and remove the styles added after for fixing that issue

Fix table header padding

---

src/components/table/index.tsx
src/components/table/sort.ts

Reverts terraware/web-components#607. I initially resolved SW-5538 in `terraware-web` by passing in a custom `sortComparator` to the species deliverable table. I then decided to go a step further and make the changes in `web-components` to be available for other tables in the future, but although these changes passed tests in `web-components`, they broke the tests in `terraware-web`.
Reverting this change for now.

Revert "SW-5538: Table column sorting for Species table for Species List Deliverable doesn't seem to work"

---

src/components/MultiSelect/index.tsx
src/components/MultiSelect/styles.scss

This PR adds missing hover & active/open styles to the `MultiSelect` component.

SW-5567: Species multi select fields are missing hover/active styling

---

src/components/DialogBox/DialogBox.tsx
src/stories/DialogBox.stories.tsx

This PR includes changes to resolve an issue where the `DialogBox` component was stopping click event propagation which was preventing the `Dropdown` component from functioning correctly when rendering within the `DialogBox` component.
Changes include restoring click event propagation and reworking the container click event handler to check if the click event target is the dialog box container before calling `onClose`.

SW-5532: Can't click out of native/non-native dropdown without selecting an option first

---

src/components/Badge/index.tsx

This PR includes changes to the `Badge` component to allow nesting within paragraphs.
Currently in `terraware-web` there are two very large warnings that take up most of the console, these changes will resolve those warnings and clean up the console.

Fix invalid DOM nesting warnings in console

---

src/components/Navbar/NavItem.tsx
src/components/Navbar/styles.scss

For custom label nav items, we need to keep the main 'nav-item' class, to keep hover, active, etc styles

Fix custom nav item

---

src/components/Navbar/styles.scss

This PR includes applies a `min-width` to the optional `icon` in `NavItem`, to prevent the icon from rendering at smaller size when the label text wraps multiple lines.

SW-5846: [Visual Bug] Icon in Application progress nav is the wrong size

---

src/components/Textfield/Textfield.tsx

This PR adds an `onFocus` prop to the `Textfield` component to trigger some code when the "Document Name" field is focused in the Add New Document view.

SW-5781: Add default file name (project + template) when people create a new document

---

src/components/Autocomplete/Autocomplete.tsx

Autocomplete renders a < ul > with < li > children. By default those < li > children have the label of the option as key, and sometimes labels could be the same, so it generates this error:
`Encountered two children with the same key, ``. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`
MUI Autocomplete has a renderOption prop to change that default behaviour, so we need to add it to our Autocomplete component to allow using it

Add renderOption prop to autocomplete

---

src/components/DialogBox/styles.scss

This PR includes a small style change to fix white text on a white background in `DialogBox`s with no footer.
Context:
The display mode of the variable popover renders no action buttons in the footer, and therefore no footer. Currently, the styles for  a`DialogBox` without a footer are defined such that the background & foreground colors are the same (both white). This resulted in the display fields in the variable popover to appear blank/empty.
Here are screenshots from Terraware with the style change in this PR:

SW-5918: Doc producer - Missing section display mode variable popover

---

src/components/Textfield/Textfield.tsx

This PR includes a fix for an issue causing asterisks to appear on a line by themselves when input fields are `required` with an empty value for `label`.

SW-5973: Remove extraneous asterisk

---

src/components/TextTruncated/index.tsx

In development, the following error showed up on several pages, because of `TextTruncated`'s default display if `stringList` was empty and `placeHolder` was undefined:
```
<div> cannot appear as a descendant of <p>
```
This error annoyed me so I decided to create a PR to fix it.

Fix react nesting warning

---

src/components/Tabs/index.tsx

This PR adds a `tabStyle` prop to the `Tabs` component to remove excess padding on the new Project Profile Pages or apply other style modifications. Currently, padding is applied by both the `Page` and `Tabs` components in the new Project Profile Pages.

SW-6812: Add Deliverables tab to Project Profile in Console

---

src/components/Tabs/index.tsx
src/stories/Tabs.stories.tsx

Design and Product decided they no longer want the border on the bottom of our tabs component, so make it optional but make the default false.
Before:
After:

SW-6963 Remove tabs border, make it optional

---

src/components/table/TableCellRenderer.tsx
src/components/table/types.ts

This allows for a fix of some console warnings that always show up during the playwright tests, making it harder to see the actual output of playwright.

Allow component specification of TableCellRenderer

---

src/components/Map/MapDrawer.tsx
src/components/Map/MapLegend.tsx
src/components/Map/styles.scss
src/stories/MapDrawer.stories.tsx
src/stories/MapLegend.stories.tsx

Title Overflow
Bigger size
Close and open behavior
[Screen Recording 2025-07-24 at 4.25.22 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/NOxkRPuhAfT4F7nmdXtG/8f4d8993-e88f-4d4b-b353-68f16e6ef481.mov" />](https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/8f4d8993-e88f-4d4b-b353-68f16e6ef481.mov)
This will only show on desktop. Tablet/mobile will not use this component and instead be handled by a different component. The Map Container will handle rendering the correct component.
Content will be implemented separately on the consumer side, on terraware-web. It will leverage tables, images and other components. The drawer itself simply behaves as a container.

Implemented map drawer for desktop

---

src/components/Map/MapBox.tsx
src/components/Map/MapLegend.tsx
src/stories/MapMarker.stories.tsx

Markers that are selected will have a different style. `selected` state is expected to be managed by the client.

Added selected marker style

---

src/components/Map/MapBox.tsx
src/components/Map/MapContainer.tsx
src/components/Map/styles.scss

Opening and closing drawers will remember map placement since it hides the map instead of re-rendering it.
[Screen Recording 2025-08-07 at 5.09.57 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/NOxkRPuhAfT4F7nmdXtG/acb14094-f7b3-4122-81f1-72e37f6f11ae.mov" />](https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/acb14094-f7b3-4122-81f1-72e37f6f11ae.mov)
On screen resizes, a listener is added to properly adjust the map size. Another effect is added to adjust sizes when drawer opens/closes. This is not super efficient but users are not expected to constantly resize their screen.
[Screen Recording 2025-08-07 at 5.25.48 PM.mov <span class="graphite__hidden">(uploaded via …

Fix map resetting and not resizing on mobile devices
