terraware/web-components

- package.json
- src/components/Select/Select.tsx
- src/components/Select/SelectT.tsx
- src/index.ts
- src/stories/Select.stories.tsx
Introduced SelectT (copy of Select with object type made into a generic)
> SW-1541 Add complex objects support to Select component

- .github/scripts/commit-message.js
- .github/workflows/design-workflow.yml
- package.json
- yarn.lock
Github action workflow automating design workflow updates + PR creation
> web-components GitHub action to automate design updates PR creation

- style-dictionary/download-json.js
- style-dictionary/zero-height-files.json
@constanzauanini the parallel downloads are failing in github action (i think this needs to be serialized for github action alone). For now just cleaning up errors/info so I can debug further.
> write info and error to stdout/stderr in download json file

- package.json
- src/components/Autocomplete/Autocomplete.tsx
- src/components/Autocomplete/styles.scss
- src/index.ts
- src/stories/Autocomplete.stories.tsx
> SW-1558 Autocomplete with new label

- package.json
- src/components/Textfield/Textfield.tsx
- src/stories/TextfieldNew.stories.tsx
> SW-1598 number in textfield

- package.json
- src/components/Select/styles.scss
I don't think we need to set this height. I'm testing without it and no problems
> Remove height of container

- package.json
- src/components/table/TableCellRenderer.tsx
- src/components/table/TableHeader.tsx
- src/components/table/TableHeaderItem.tsx
- src/components/table/index.tsx
- src/components/table/types.ts
- src/stories/Table.stories.tsx
- updated table story to demonstrate changes
> SW-1919  allow custom styles in table cell/header

- package.json
- src/components/Textfield/Textfield.tsx
- this was being harcoded, removed that
- won't default to any value now
> SW-1954 don't default number inputs to '0'

- package.json
- src/components/DialogBox/styles.scss
> SW-1811 Adding margin to dialog box on web-mobile

- package.json
- src/components/IconTooltip/index.tsx
Quick follow-up PR, forgot to `import React` 😅
> SW-1752: Quick Follow-Up

- package.json
- src/components/IconTooltip/index.tsx
This PR updates the `IconTooltip` component to open when clicked on mobile.
> SW-1760: Dashboard Total Active Accessions Tooltip

- src/components/table/TableHeader.tsx
- src/components/table/index.tsx
- src/stories/Table.stories.tsx
- change thead to TableHead
- removing TableContainer
> SW-1901 Enable Sticky Header

- src/components/table/index.tsx
- turned out that removing TableContainer was not necessary
- put the TableContainer back in
- add overflowX visible to make the header sticky
> Add TableContainer Back

- package.json
- src/index.ts
Because I didn't follow all the directions :shame:
> Re-export TextTruncated

- package.json
- src/components/TextTruncated/index.tsx
one more thing I missed... sorry, this problem didn't show up in storybook so I missed it
> TextTruncated import React

- renovate.json
- Set `:preserveSemverRanges` preset to preserve `^`s
- Runs each weekend so PRs are ready by Monday morning
- Give 3 days for package versions to stabilize
- Label Major PRs as `UPDATE-MAJOR`
> Update Renovate Settings

- package.json
- src/components/Select/styles.scss
- move disabled bg color from readonly to disabled
> SW-2119 Fix readonly vs disabled bgcolor style on select component

- .github/workflows/develop.yml
- package.json
- src/theme.ts
- set xl breakpoint to 1400px
- this is to support transitioning the background style on the home page
- version 2.0.0 (visual updates)
> SW-2168 Add Custom 1400px Breakpoint

- package.json
- src/components/Autocomplete/styles.scss
- src/components/Select/styles.scss
- src/components/Textfield/styles.scss
- update corner radii
- make sure border and label colors correct
> SW-2154 Update Input Fields

- package.json
- src/components/DatePicker/DatePicker.tsx
- src/components/Textfield/Textfield.tsx
- src/stories/DatePicker.stories.tsx
- src/stories/TextfieldNew.stories.tsx
Add optional props to these components to allow them to be set
to auto-focus on render.
> Add autoFocus to TextField and DatePicker

- package.json
- src/components/table/TableCellRenderer.tsx
- src/components/table/TableHeader.tsx
- src/components/table/index.tsx
- default cell borders
- rm bottom padding of pagination block
- make header hideable
> Table Updates

- src/components/table/TableCellRenderer.tsx
- src/components/table/TableHeader.tsx
- src/components/table/index.tsx
> Use More Specific Selector for Table Cells

- .storybook/preview-head.html
- same solution used in terraware-web
- at some point we may need to converge
> Add font weights to storybook

- .storybook/preview-head.html
Same as this PR https://github.com/terraware/web-components/pull/145
> Fix font weights on visual updates branch

- package.json
- src/components/Navbar/styles.scss
This PR addresses some additional follow-up items.
> SW-2251: Update NavBar for nested hierarchy navigation (follow up #2)

- package.json
- src/components/DialogBox/DialogBox.tsx
- src/components/DialogBox/styles.scss
- skrim off by default
- should be on for destructive actions only
- remove blur
- change background to gradient
> SW-2159 Update Dialog Skrim

- package.json
- src/components/DatePicker/styles.scss
- src/components/Select/styles.scss
- src/components/TextTruncated/index.tsx
- src/components/Textfield/styles.scss
- update Dropdown menu border-radius
- update DatePicker border-radius
- change TextTruncated link color
- apply active border width to TextField on active
> Some Style Updates

- package.json
- src/components/Navbar/NavItem.tsx
- (I have not been able to reproduce)
- reported errors seem to indicate null dereferencing error on NavItem component
- add some stricter null checking
> SW-2449 NavBar Load Errors

- package.json
- src/components/Navbar/Navbar.tsx
- src/components/Textfield/styles.scss
> SW-2488 and SW-2487 Decrease size of “x” for mobile nav to match menu icon and fix disabled textfield active style

- package.json
- src/components/Navbar/styles.scss
- src/components/Textfield/styles.scss
- src/stories/TextfieldNew.stories.tsx
> SW-2489 / SW-2453 fix nav font-family and update search icon

- package.json
- src/components/Checkbox.tsx
> SW-2490 Fix disabled checkbox style (opacity)

- package.json
- src/components/Autocomplete/Autocomplete.tsx
- src/stories/Autocomplete.stories.tsx
- also fix double event handling for non-free-solo autocompletes
> Fix auto-complete equality check for complex objects

- package.json
- src/components/Autocomplete/Autocomplete.tsx
- src/index.ts
- src/stories/Autocomplete.stories.tsx
- was currently reusing the label
> SW-2520 add a placeholder to autocomplete inputs

- package.json
- src/components/Autocomplete/Autocomplete.tsx
- src/components/Autocomplete/styles.scss
- src/stories/Autocomplete.stories.tsx
> Add error text to autocomplete component

- package.json
- src/components/table/index.tsx
- src/components/table/types.ts
- src/stories/Table.stories.tsx
- Reorder of columns was done on accession table instead of table component. Move that behavior to table component.
- Add another column to table story to test reorder there
> SW-2513 Move reorder functionality to web components

- package.json
- src/components/Autocomplete/Autocomplete.tsx
- avoids some corner case issues
> web-components: fix autocomplete issue where label selection was incorrect

- package.json
- src/components/Navbar/NavItem.tsx
- src/components/Navbar/styles.scss
- src/stories/Navbar.stories.tsx
- we want to allow opening the hierarchy without selecting a menu item
> SW-2575 Allow toggling open state of nav hiearchy root

- package.json
- src/components/table/EnhancedTableToolbar.tsx
- src/components/table/index.tsx
- src/stories/Table.stories.tsx
> SW-2596 support disabled top bar buttons in table

- package.json
- src/components/Autocomplete/Autocomplete.tsx
- src/components/Autocomplete/styles.scss
> SW-2591 SW-2592 Error and disabled styles for autocomplete

- package.json
- src/components/Button/styles.scss
Adding a 5px margin on button element to guarantee the needed space for focus outline
> SW-2609 Fix outline cut off on Button component

- .github/dependabot.yml
Lets see how this works before we can apply it on terraware-web as well
> Enable version upgrades by dependabot

- package.json
- yarn.lock
This reverts commit bc60a3b8b6a6a8c1e6de2c0c2383cc714d3431f5.
> Revert "Revert "Bump @mui/styles from 5.9.3 to 5.11.2 (#225)" (#234)"

- package.json
- src/components/Message/Message.tsx
This is needed for showing links on the body of the message
> Allow JSX.Elements on Message body

- package.json
- src/components/Autocomplete/Autocomplete.tsx
- src/stories/Autocomplete.stories.tsx
> Add tooltip to autocomplete

- .github/workflows/auto-version.yml
- .github/workflows/open-pr.yml
- Comment on PR to apply a patch, minor, or major label to the PR
- Auto-add patch if not a bot
- On PR close, if merged, add a commit to bump the appropriate version
> Github Action to Auto-Increment Package Version

- .github/workflows/auto-version.yml
- Use token, email, and username from terraformation-deploy user
- Secrets are in place; this should fix the version-bump job
> Auto-Increment Version Update

- src/components/Autocomplete/Autocomplete.tsx
- src/components/Dropdown.tsx
- src/components/types/index.ts
- src/index.ts
- src/stories/Dropdown.stories.tsx
- similar to dropdown for Select
> Dropdown wrapper for autocomplete

- src/components/Autocomplete/Autocomplete.tsx
- src/components/Dropdown.tsx
- src/index.ts
- src/stories/Autocomplete.stories.tsx
- src/stories/Dropdown.stories.tsx
- use single component
- use 'autocomplete' boolean option to switch behavior
> Refactor Dropdown components 

- src/components/MultiSelect/MultiSelect.test.tsx
- src/components/MultiSelect/index.tsx
- src/components/MultiSelect/styles.scss
- src/components/Pill/index.tsx
- src/components/Pill/styles.scss
- src/components/PillList/index.tsx
- src/components/PillList/styles.scss
- src/stories/MultiSelect.stories.tsx
A multiple selection dropdown component is build here. It expects a map
of identifiers (generic) to values (strings) for its options. It also
expects a onAdd and onRemove handlers for the consumer to update its
selectedOptions with.
The component shows pills for selected options with a remove button, and
the remaining options are shown in a dropdown. The onAdd handler is
called with the map key whenever one of these is clicked.
> SW-2625 Build a Multiple-Selection Dropdown Component

- .storybook/preview.js
Now the theme is initialized the same way as in terraware-web. 
Still need to update a dependency to check if this works
> SW-2712 Initialize theme the same way we do in terraware-web

- src/components/Button/styles.scss
> Change button height, to be a min height

- src/components/MultiSelect/index.tsx
- src/components/MultiSelect/styles.scss
- src/stories/MultiSelect.stories.tsx
- yarn.lock
> Make MultiSelect Disableable

- src/components/Button/Button.tsx
- src/components/Button/styles.scss
- src/stories/Button.stories.tsx
Same as passive but without a border.  See https://zeroheight.com/55ab6cc27/p/28e634-button/t/1637e9
> SW-2037 Add "ghost" button priority

- src/components/Tooltip/Tooltip.tsx
- src/index.ts
- src/stories/Tooltip.stories.tsx
To be added to icon buttons.
For the future we could consider replacing the IconTooltip with this generic version but I didn't do that here.
> SW-2530 Create generic tooltip component

- src/components/DatePicker/styles.scss
> SW-3013 Fix datepicker error state background color is missing

- src/components/Autocomplete/styles.scss
- src/components/DatePicker/styles.scss
This was the simplest solution to fix the issue described in SW-2518.  I tried to clean up some of the styles for these components and found quite a tangle that wasn't worth it to work through right now.
> SW-2518 Apply correct border color to fieldset

- src/components/Textfield/Textfield.tsx
This is added for my workaround to issue https://terraformation.atlassian.net/browse/SW-3194
> Add onBlur handler to TextField Component

- src/components/Navbar/NavItem.tsx
- src/components/Navbar/styles.scss
- src/stories/Navbar.stories.tsx
- anchor tags
- custom labels (could be anything, example a styled button)
- needed for funder portal as the designs are introducing new patterns
> Support new types of menu items in the nav bar

- src/components/BusySpinner/index.tsx
- src/components/FormBottomBar/index.tsx
- src/components/PageForm/index.tsx
- src/index.ts
- src/stories/BusySpinner.stories.tsx
- src/stories/PageForm.stories.tsx
- yarn.lock
- for reuse across apps
- removed additionalLeftButtons as it was not supported (only existed in props)
- created stories
> SW-3361 Move page form / bottom bar and spinner with skrim to web-components

- src/components/Navbar/Navbar.tsx
Updated to match spec at: https://www.figma.com/file/DftqOeGx8irCdRf7IZ4lbc/Navigation?node-id=5012-195776&t=5U7dSR3JZTtaR40P-0
> SW-2704 Move close icon to right side and make larger

- src/components/PhotoChooser/index.tsx
- src/index.ts
- also move photo chooser into it's own directory
> export PhotoChooser error type from index.ts

- vercel.json
- these error out and have no ui code to preview anyways
> Skip vercel previews for gh-pages

- src/components/PopoverMenu/Popover.tsx
- src/components/types/index.ts
- src/stories/PopoverMenu.stories.tsx
> Add destructive type popover menu item support

- package.json
- src/components/DialogBox/styles.scss
- src/components/ViewPhotosDialog/index.tsx
- src/components/ViewPhotosDialog/styles.scss
- src/index.ts
- src/stories/ViewPhotosDialog.stories.tsx
- yarn.lock
> View Photos Dialog Component

- src/components/DialogBox/styles.scss
- src/components/ViewPhotosDialog/index.tsx
- Fix initialSelectedSlide updates
- Fix empty photos list bug
- Make dialog box scroll on overflow (should be good in general I think)
> Fixes for ViewPhotosDialog

- src/components/Button/Button.tsx
- src/components/Button/styles.scss
- src/stories/Button.stories.tsx
> Add Right Icon to Buttons

- src/components/table/types.ts
This will be leveraged in terraware-web to update table column configurations with search type.
> Add Optional Search Type to Database Column Type

- src/components/PopoverMultiSelect/styles.scss
- This import broke compilation in terraware-web
- Change to a relative import to fix
> Fix Sass Import

- src/components/DatePicker/DatePicker.tsx
- Added this yesterday because of a react compile warning
- It is causing issues reported by Alex
- was able to test this locally
- guessing it was left out earlier for the same reason
> Remove DatePicker change on useEffect

- src/components/Slider/index.tsx
- src/index.ts
- src/stories/Slider.stories.tsx
- Create a Slider component
- Wraps a basic MUI Slider and adds TW styling
> SW-3632 Slider Component

- src/components/Slider/index.tsx
Allow the consuming component to set the value of the slider.
> Make Slider Value Controllable

- src/components/ViewPhotosDialog/index.tsx
- src/stories/ViewPhotosDialog.stories.tsx
- the initialSelectedSlide and open useEffects had been merged, which broke the handling of slide change (the handleChange ignores selected slide change)
- separated out the concerns, which was the right thing to do anyways
- also reorganized the code a bit
> SW-3757 View photos dialog react to initialSelectedSlide prop

- src/components/table/TableHeaderItem.tsx
- The makeStyles function returns a hook, which must not be conditionally called.
- Reorganized the code so that the hook is unconditionally called.
> SW-3771 Do Not Conditionally Render Styles Hook

- package.json
- src/components/Tabs/index.tsx
- src/stories/Tabs.stories.tsx
- yarn.lock
- copied over from funder-web, i believe the styles are the same
- added a story
- next step is to refactor funder-web to use this, which has some additional semantics
- and also use this in terraware-web
> Tabs component in web-components

- package.json
- src/index.ts
- src/stories/IntersectionObserver.stories.tsx
- yarn.lock
- Implement basic story with `react-intersection-observer` to show how it works in action
It is a pretty basic example, and implements the `react-multi-carousel` since it is a heavy component and has visible lag in rendering the photos. Under the hood the DOM is updated pretty much instantaneously so using in our PDD tool on a tall page with many sections will seem much snappier.
> SW-4199 Intersection Observer story

- src/components/TextTruncated/index.tsx
- src/stories/TextTruncated.stories.tsx
- for large lists, the popper can get very large and out of the fold
> Sw-4530 Use fixed height with scroll on TextTruncated popper

- package.json
- src/components/MultiSelect/index.tsx
- [Add onBlur prop to MultiSelect](https://github.com/terraware/web-components/pull/447/commits/6d38b7d67f77e41f256515fff4bbc8203f2267dd)
- [Prettier reformat](https://github.com/terraware/web-components/pull/447/commits/ee348e24a46a61929f66c8514d6d5b577880b9cf)
> Add onBlur prop to MultiSelect

- src/components/table/EnhancedTableToolbar.tsx
- src/components/table/EnhancedTableToolbarV2.tsx
- src/components/table/index.tsx
- src/stories/Table.stories.tsx
V2 wrapper that changes functionality if the `enhancedTopBarSelectionConfig` is there or not. The wrapper will decorate the config with the necessary functionality to render the text without passing more data than necessary into the toolbar component.
> SW-4503 Implement v2 enhanced top bar with select all, select none, enhanced selection text

- src/components/Message/Message.tsx
- was missing the curly braces
> SW-4720 Render value of body in Message

- package.json
- src/components/table/TableHeader.tsx
- src/components/table/index.tsx
- src/utils/text.ts
> SW-4565 / SW-3514 Make table headers title case and don't overflow

- package.json
- src/components/table/EnhancedTableToolbar.tsx
- src/stories/Table.stories.tsx
> SW-4747 Fix styling of enhanced toolbar, add story control for changing row count

- src/components/Separator/index.tsx
- src/index.ts
- src/stories/Separator.stories.tsx
- Adjustable height that defaults to 32px
> Separator component

- src/components/Badge/index.tsx
- src/index.ts
- src/stories/Badge.stories.tsx
The `labelColor` will match the `borderColor` unless specified explicitly.
> Create badge component with label, labelColor, backgroundColor, borderColor args

- .prettierrc
- package.json
- src/components/PopoverMenu/Popover.tsx
- src/components/types/index.ts
- src/stories/PopoverMenu.stories.tsx
> Add ability to disable popover menu items

- package.json
- src/components/PhotoChooser/index.tsx
- src/stories/PhotoChooser.stories.tsx
- callback when files are selected was broken
- callback was firing only if there were changes to the selection
> SW-5062 Fix regression in photo chooser

- package.json
- src/components/Tabs/index.tsx
- src/stories/Tabs.stories.tsx
> Add ability to optionally add icon to a tab

- package.json
- src/components/Dropdown.tsx
- src/components/Icon/Icon.tsx
- src/components/Select/Select.tsx
- src/components/Select/SelectT.tsx
- src/stories/Select.stories.tsx
- Add select styling props since useStyles is deprecated and we need the ability to control the styling for the participant project dropdown
> SW-5122 Add ability to style the Select component

- package.json
- yarn.lock
This reverts commit caf8e919b3797886bbd138ef01f233da1a5def47.
> Revert "Bump @mui/material from 5.15.3 to 5.15.15 (#502)"

- package.json
- rc should have been off next patch version, 2.16.3
> Fix package.json version again to trigger npm publish

- src/components/Tabs/index.tsx
This PR includes a handful of style updates to the `Tabs` component.
> SW-5312: Update styles for Tab Group/Tab component

- src/components/DialogBox/styles.scss
This PR includes a handful of style updates to the `DialogBox` component.
> SW-5082: Update border and background styles for Dialog Box component

- src/components/Tabs/index.tsx
This PR includes some follow-up style updates that weren't included in the previous PR.
> SW-5312: Update styles for Tab Group/Tab component (follow-ups)

- src/components/table/TableCellRenderer.tsx
- src/components/table/types.ts
Add style prop so we can set width to the columns of the table
> SW-5420 Add style to table columns

- src/components/Autocomplete/Autocomplete.tsx
- src/components/Button/Button.tsx
- src/components/Checkbox.tsx
- src/components/DatePicker/DatePicker.tsx
- src/components/Dropdown.tsx
- src/components/ErrorBox/ErrorBox.tsx
- src/components/FileChooser/index.tsx
- src/components/Icon/Icon.tsx
- src/components/IconTooltip/index.tsx
- src/components/MultiSelect/index.tsx
- src/components/Navbar/Navbar.tsx
- src/components/Note.tsx
- src/components/PhotoChooser/index.tsx
- src/components/PopoverMenu/index.tsx
- src/components/Select/Select.tsx
- src/components/Select/SelectT.tsx
- src/components/SummaryBox.tsx
- src/components/TextTruncated/index.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/table/EnhancedTableToolbar.tsx
- src/components/table/TableCellRenderer.tsx
- src/components/table/TableHeader.tsx
- src/components/table/TableHeaderItem.tsx
- src/components/table/index.tsx
- src/components/table/types.ts
- src/stories/Autocomplete.stories.tsx
- src/stories/Checkbox.stories.tsx
- src/stories/MultiSelect.stories.tsx
- src/stories/Table.stories.tsx
This PR includes changes to remove instances of `makeStyles` in this repo, as well as adding `sx` and/or `style` props to some components to support removing `makeStyles` in the `terraware-web` repo.
> SW-53417: Remove makeStyles everywhere in Terraware web

- package.json
- yarn.lock
Just a quick PR to resolve a warning for a missing dependency
> Fix terminal warning for missing dev dependency

- style-dictionary/build-theme.mjs
ESList complains about the theme that gets built.  Update the builder script so that it's happy.
> SW-5494 Update theme builder to work with ESLint

- src/components/table/TableCellRenderer.tsx
This one got lost in a merge of my last PR
> SW-5443 Fix table row border color

- src/components/table/TableHeaderItem.tsx
This PR resolves a padding issue in table column headers.
> SW-5510: Left and right padding missing from table column headers after style changes

- src/components/table/index.tsx
- src/components/table/sort.ts
This PR includes a change to support sorting by nested row properties in the `Table` component.
> SW-5538: Table column sorting for Species table for Species List Deliverable doesn't seem to work

- src/components/Navbar/NavItem.tsx
- src/components/Navbar/styles.scss
- src/stories/Navbar.stories.tsx
disabled button with 50% opacity. This is required for the application nav.
> Added disabled state to nav item

- src/components/MultiSelect/index.tsx
- src/components/MultiSelect/styles.scss
> SW-5606 Add error text on Multiselect

- package.json
- src/components/Checkbox.tsx
- src/stories/Checkbox.stories.tsx
> SW-5761 Add indeterminate state to checkbox

- package.json
- src/components/Autocomplete/Autocomplete.tsx
- src/stories/Autocomplete.stories.tsx
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/62d618eb-553e-400d-9da8-c52a7d4c9adc.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/NOxkRPuhAfT4F7nmdXtG/62d618eb-553e-400d-9da8-c52a7d4c9adc.mov">Screen Recording 2024-09-17 at 12.34.28 PM.mov</video>
> Upgrades AutoComplete to better support async fetching of results

- src/components/table/index.tsx
- src/stories/Table.stories.tsx
> Add the possibility to add a comment between the table and the pagination component

- src/components/Textfield/Textfield.tsx
- src/stories/TextfieldNew.stories.tsx
Allow length limits to be set on text inputs.
> SW-6577 Add maxLength property to TextField

- src/components/FormBottomBar/index.tsx
- src/components/PageForm/index.tsx
Needed to make the new settings page work correctly
> SW-6604 Add bottom form bar desktop offset

- src/components/PlacementWrapper/index.tsx
- src/index.ts
- src/stories/PlacementWrapper.stories.tsx
Add component for specifying placement of an object around another object
> Add component for specifying placement of an object around another object

- package.json
- src/components/Tabs/index.tsx
- src/stories/Tabs.stories.tsx
This PR includes a minor change to rename a `Tabs` prop: `onTabChange` --> `onChangeTab`
> SW-6955: Browser back button doesn't work on some pages

- src/components/Map/MapBox.tsx
- src/components/Map/MapDateSliderControl.tsx
- src/stories/MapDateSlider.stories.tsx
- src/utils/date.ts
> Added date sliders

- package.json
- src/components/Textfield/Textfield.tsx
- src/components/Textfield/TruncatedTextArea.tsx
- src/components/Textfield/styles.scss
- src/stories/TextfieldNew.stories.tsx
- yarn.lock
[Screen Recording 2025-08-29 at 4.04.31 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/d1dbef6a-f1b6-4f31-b30e-6c07c6dff994.mov" />](https://app.graphite.dev/user-attachments/video/d1dbef6a-f1b6-4f31-b30e-6c07c6dff994.mov)
> Added markdown support for TextField
